#!/bin/sh
PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

# Begin real processing below this line
. /usr/share/initramfs-tools/hook-functions
copy_exec /usr/local/bin/evmctl /sbin
copy_exec /usr/bin/keyctl /sbin
cp -r /etc/keys $DESTDIR/etc

